### PR TITLE
Fixes for Julia v0.6 and GeometryTypes 0.4

### PR DESCRIPTION
**Pull request by rdeits**
cc @SimonDanisch I think I added enough `.+ 1`s everywhere 😉

### CODE REVIEW

**Comment by rdeits** [comment]
This requires https://github.com/JuliaGeometry/GeometryTypes.jl/pull/93 and https://github.com/JuliaGeometry/GeometryTypes.jl/pull/91

**Comment by rdeits** [comment]
Failures on nightly are a Julia bug: https://github.com/JuliaLang/julia/issues/22179

**Comment by SimonDanisch** [comment]
Wait, have you actually seen: https://github.com/JuliaIO/MeshIO.jl/tree/sd/staticarrays

**Comment by rdeits** [comment]
Derp, no, I hadn't

**Comment by SimonDanisch** [comment]
Sorry for not making it more obvious... I'm a bit behind maintaining all these packages -.-

**Comment by rdeits** [comment]
No problem. I've updated this branch again to be compatible with https://github.com/JuliaGeometry/GeometryTypes.jl/pull/97 . I think the use of `reinterpret()` here helps a lot with clarifying what's going on (and saves two whole additions, too! :wink: )

**Comment by rdeits** [comment]
Is this OK to merge? I'd like to get the GeometryTypes mesh ecosystem working in time for JuliaCon 😄

**Comment by rdeits** [comment]
thanks!

**Pull request merged**
