### PR TITLE
WIP: Started with VTKXML export

### PR DESCRIPTION
**Pull request by KristofferC**
Haven't tested in properly yet but thought I would put it here to get some potential feedback.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Looks pretty good to me =)
Guess, we'll soon have to put things together properly and write some tests... then we'll see how this all works out!

**Comment by sjkelly** [comment]
Just saw this @KristofferC . This would be great to have!

**Comment by SimonDanisch** [comment]
Wait, why was this not merged? This still looks like a good pr, doesn't it?

**Comment by KristofferC** [comment]
WriteVTK.jl is very good. Makes more sense to use that or write a wrapper that uses it.

**Comment by SimonDanisch** [comment]
Good to know, thanks! :)

**Pull request closed without merging**
