### PR TITLE
Support Julia 1.3

### PR DESCRIPTION
**Pull request by devmotion**
MeshIO holds back GeometryBasics (and hence also GridLayoutBase) in the tests of Makie with Julia 1.3 (https://github.com/JuliaPlots/Makie.jl/pull/1244). CI should reveal any potential issues with Julia 1.3 🙂

### CODE REVIEW

**Comment by devmotion** [comment]
Test errors look similar to https://github.com/JuliaIO/FileIO.jl/issues/345, maybe it's an issue upstream. I'll investigate it more closely when I'm back at my computer.

**Comment by devmotion** [comment]
Tests pass now with Julia 1.3. The problem was that `filter(f, ::Tuple)` is not defined in Julia 1.3. I used the opportunity to clean the list of imports and fix the deprecations in the tests as well.

**Comment by devmotion** [comment]
@SimonDanisch The PR is ready for review :slightly_smiling_face:

**Comment by SimonDanisch** [comment]
Thank you :)

**Pull request merged**
