### PR TITLE
Update MeshIO for GeometryBasics refactor

### LINKED ISSUE #80: Information are lost when mesh has different normals per position
When a mesh is loaded using `load("...")`, the faces are represented "directly" as 3 points, instead of being references to the `position` array. This makes impossible to distinguish the attributes of different vertices that have the same positions (e.g. normals and uv coords).

A simple cube is a good example of such object:
```
# cube.obj
#
 
g cube
 
v  0.0  0.0  0.0
v  0.0  0.0  1.0
v  0.0  1.0  0.0
v  0.0  1.0  1.0
v  1.0  0.0  0.0
v  1.0  0.0  1.0
v  1.0  1.0  0.0
v  1.0  1.0  1.0

vn  0.0  0.0  1.0
vn  0.0  0.0 -1.0
vn  0.0  1.0  0.0
vn  0.0 -1.0  0.0
vn  1.0  0.0  0.0
vn -1.0  0.0  0.0
 
f  1//2  7//2  5//2
f  1//2  3//2  7//2 
f  1//6  4//6  3//6 
f  1//6  2//6  4//6 
f  3//3  8//3  7//3 
f  3//3  4//3  8//3 
f  5//5  7//5  8//5 
f  5//5  8//5  6//5 
f  1//4  5//4  6//4 
f  1//4  6//4  2//4 
f  2//1  6//1  8//1 
f  2//1  8//1  4//1 
```

Note that the positions appear with different attributes per face. When this mesh is loaded with this library, I don't see a way to properly retrieve the correct attributes per vertex.

IMO, each triangle should be represented by 3 vertices (instead of 3 positions), whereas each vertex is composed by references to the positions, normals and uv vectors, which already exist.

This change would make this library suitable for general use in mesh processing

### LINKED ISSUE #94: load file with multi meshes
usually, complex meshes are a combination of multiple meshes and textures (colors), hence  having support for this directly here would be a really nice functionality.

### PR DESCRIPTION
**Pull request by ffreyer**
(I moved the branch to MeshIO for this one)

Changes for https://github.com/JuliaGeometry/GeometryBasics.jl/pull/219

TODO:

- [x] 2dm
- [x] gts
- [x] ifs
- [x] msh
- [x] obj
- [x] off
- [x] ply
- [x] stl
- [x] test (locally)

Closes #94 (materials, face groups/objects now loaded with obj files)
Fixes #80

### CODE REVIEW

**Comment by ffreyer** [comment]
Added the Sponza model from https://casual-effects.com/data/ with only two of the groups/sub-meshes present and all textures removed. That should be enough to test correct loading of group names, "usemtl" tags,`mesh.views` and some mtl file parsing, without excessive bulk.

**Comment by SimonDanisch** [comment]
This is a breaking change, that changes the load method:
image

**Comment by ffreyer** [comment]
Oh, true. I didn't have that type at some stages of doing the refactor, so I probably change it then. But I think this is also more in line with other load methods

**Comment by ffreyer** [comment]
obj, ply and stl use this already

**Review by SimonDanisch — APPROVED** [review]

**Pull request merged**
