### PR TITLE
add support for abaqus inp format

### PR DESCRIPTION
**Pull request by KristofferC**
I think the best approach (to start) is just to have each different mesh have a different type and document it. The mesh formats are so different and the metadata they carry is so different that putting them in the same type is in my view not feasible.

Open for comments.

TODO: 
- [ ] Documentation
- [ ] Register in FileIO

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Looks great! 
Just a warning: I'll be traveling to Boston, so I won't have time to look into this any time soon ;)

**Comment by KristofferC** [comment]
There is no rush

**Comment by TeroFrondelius** [comment]
Hi. Is there a reason why this pull request has not been accepted? I really like this repo idea, but we cannot contribute if pull request acceptance will take months. 

We have some ready io code in JuliaFEM repo which we would like to move or reimplement in FileIO.jl framework.

**Comment by ahojukka5** [comment]
Our current implementations related to reading inp files. We have a type Mesh containing everything necessary to store information about discretized geometry of model

https://github.com/JuliaFEM/JuliaFEM.jl/blob/master/src/preprocess.jl#L19

This Mesh object is constructed from Abaqus inp files in

https://github.com/JuliaFEM/JuliaFEM.jl/blob/master/src/preprocess_abaqus_reader.jl

We have also another file,

https://github.com/JuliaFEM/JuliaFEM.jl/blob/master/src/abaqus.jl

mainly because we are also interested of other things of model and simulation, not only discretized geometry.

**Comment by SimonDanisch** [comment]
Lol, completely forgot about this! I'll merge it if you want :)

**Comment by KristofferC** [comment]
Nah, it's ok :)

**Comment by SimonDanisch** [comment]
But it looks kinda cool :P

**Pull request closed without merging**
